OUTPUT:


ERROR:
Traceback (most recent call last):
  File "/home/ethan/repository/few-shot/LLM_Routing/llm/extra_info_pseudo-code_v2/solution/single/KTSP/15/city_15_instance_1/0/0/solution_r0.py", line 93, in <module>
    best_tour, best_tour_cost = GVNS()
                                ^^^^^^
  File "/home/ethan/repository/few-shot/LLM_Routing/llm/extra_info_pseudo-code_v2/solution/single/KTSP/15/city_15_instance_1/0/0/solution_r0.py", line 81, in GVNS
    S_double_prime = VND(S_prime)
                     ^^^^^^^^^^^^
  File "/home/ethan/repository/few-shot/LLM_Routing/llm/extra_info_pseudo-code_v2/solution/single/KTSP/15/city_15_instance_1/0/0/solution_r0.py", line 61, in VND
    S_double_prime = local_search(S_prime, Np=p)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ethan/repository/few-shot/LLM_Routing/llm/extra_info_pseudo-code_v2/solution/single/KTSP/15/city_15_instance_1/0/0/solution_r0.py", line 50, in local_search
    cost = calculate_tour_param(dist_matrix, S_prime)
           ^^^^^^^^^^^^^^^^^^^^
NameError: name 'calculate_tour_param' is not defined. Did you mean: 'calculate_tour_cost'?


