OUTPUT:


ERROR:
Traceback (most recent call last):
  File "/home/ethan/repository/few-shot/LLM_Routing/llm/extra_info_pseudo-code_v3/solution/multiple/mTSPMD/10/P-n23-k8/3/2/solution_r1.py", line 69, in <module>
    pop, log, hof = main()
                    ^^^^^^
  File "/home/ethan/repository/few-shot/LLM_Routing/llm/extra_info_pseudo-code_v3/solution/multiple/mTSPMD/10/P-n23-k8/3/2/solution_r1.py", line 63, in main
    population, log = algorithms.eaSimple(population, toolbox, cxpb=crossover_prob, mutpb=mutation_prob, 
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ethan/miniconda3/envs/llm_routing/lib/python3.11/site-packages/deap/algorithms.py", line 151, in eaSimple
    for ind, fit in zip(invalid_ind, fitnesses):
  File "/home/ethan/repository/few-shot/LLM_Routing/llm/extra_info_pseudo-code_v3/solution/multiple/mTSPMD/10/P-n23-k8/3/2/solution_r1.py", line 39, in evaluate
    return tuple(sum(distance_matrix[route[i-1], route[i]] for i in range(1, len(route))),)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'numpy.float64' object is not iterable


